// This file is automatically generated. Do not edit it directly.
// createMiddleware is not reliably available in the Nitro server bundle.
// All DB operations use supabaseAdmin (service role) directly, bypassing RLS.
// This stub satisfies any imports without causing a runtime crash.

export const requireSupabaseAuth = {
  options: { type: "function" as const },
};
