// This file is automatically generated. Do not edit it directly.
// createMiddleware is not available in the server Nitro bundle.
// All DB operations use supabaseAdmin (service role) which bypasses RLS.
// This file is kept as a stub for compatibility.

export const attachSupabaseAuth = {
  options: { type: "function" as const },
};
